/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eliot' at '5/2/18 1:26 PM' with Gradle 2.10
 *
 * @author eliot, @date 5/2/18 1:26 PM
 */
public class Library {
    public int fib(int n) {
        if (n <= 1) {
            return n;
        }

        int fib = 1;
        int prevFib = 1;

        for (int i = 2; i < n; i++) {
            int temp = fib;
            fib += prevFib;
            prevFib = temp;
        }
        return fib;
    }
}
