import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'eliot' at '5/2/18 1:26 PM' with Gradle 2.10
 *
 * @author eliot, @date 5/2/18 1:26 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
        assertEquals(55, classUnderTest.fib(10));
    }
}
